version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: ma-bdd
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - bdd_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin

volumes:
  bdd_data: